name: build-and-test

on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: ./test_server.sh